# Generated by Django 4.1.7 on 2023-03-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_meetingtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=None)),
                ('end_time', models.TimeField(default=None)),
                ('members', models.IntegerField()),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.meetingroom')),
            ],
        ),
    ]
